export type AppLocale = 'zh_TW' | 'zh_CN' | 'en'
export type AppLocalePreference = 'auto' | AppLocale

export const detectAppLocale = (): AppLocale => {
  const lang = navigator.language
  if (lang.startsWith('zh-TW')) return 'zh_TW'
  if (lang.startsWith('zh')) return 'zh_CN'
  return 'en'
}

export const resolveAppLocale = (preference?: AppLocalePreference): AppLocale => {
  if (!preference || preference === 'auto') {
    return detectAppLocale()
  }

  return preference
}

const TEXT = {
  zh_TW: {
    me: '我',
    aiInvokeLabel: '@ai',
    aiInvokeDescription: '呼叫房間 AI',
    aiInsertTitle: '插入 @ai 指令',
    aiPromptPlaceholder: '輸入訊息... 輸入 @ai 可呼叫房間 AI',
    privateChatPlaceholder: '傳送私密訊息給 @{username}...',
    privateChatActive: '私密對話中（僅傳送給 @{username}）',
    cancel: '取消',
    aiUnsupportedInPrivate: '@ai 目前不支援私聊模式。',
    aiPromptRequired: '請在 @ai 後面輸入問題。',
    aiBusy: 'AI 還在回覆上一則問題，請稍候。',
    aiCooldown: '@ai 冷卻中，請 30 秒後再試。',
    aiLoading: 'AI 正在整理回覆...',
    aiReplied: 'AI 已回覆到聊天室',
    aiReplyFailed: 'AI 回覆失敗，請稍後再試。',
    aiMessageTitle: 'AI 訊息',
    privateChatTitle: '點擊開始私聊',
    privateChatCancelTitle: '取消私聊',
    privateChatBadge: '私聊',
    privateMessageTo: '私密傳送給 @{username}',
    privateMessageIncoming: '私密訊息',
    emptyMessage: '訊息不可為空。',
    messageTooLarge: '訊息大小不可超過 256KiB。',
    userOffline: '該使用者已離線，無法進行私聊。',
    messageLimitReached: '已達訊息長度上限（{max} 字元）。',
    sendMessage: '送出',
    chatTab: '聊天',
    aiTab: 'AI',
    insertPageLink: '插入目前頁面連結',
    closeChat: '關閉聊天',
    hideFloatingButtons: '隱藏懸浮按鈕',
    hideFloatingButtonsSuccess: '懸浮按鈕已完全隱藏，可在擴充功能設定頁面重新顯示。',
    chatButtonTitle: '聊天室',
    summaryButtonTitle: '網頁摘要與對話',
    themeButtonTitle: '切換主題',
    settingsButtonTitle: '設定',
    emptyRoomTitle: '目前聊天室沒有人發言。',
    emptyRoomDescription: '輸入訊息並按下 Enter 開始聊天。',
    setupNamePlaceholder: '輸入你的暱稱...',
    setupAvatarHint: '點擊頭像可以隨機更換頭像',
    setupStart: '開始聊天',
    avatarFileTypeError: '僅支援 PNG、JPEG、WebP 圖檔',
    copied: 'Copied',
    copy: 'Copy',
    copyWithUrl: '含連結複製',
    copyMessageTitle: '複製此則訊息',
    copyWithUrlTitle: '複製此則訊息與來源頁面連結',
    copiedTitle: '已複製',
    openPage: '開啟頁面',
    openPageTitle: '開啟這則訊息對應的原始頁面',
    pageLabel: '頁面',
    ban: '封鎖',
    unban: '取消封鎖',
    banTitle: '封鎖此人與他觸發的 AI',
    unbanTitle: '取消封鎖此人',
    likeTitle: '按讚',
    dislikeTitle: '倒讚',
    copySuccess: '已複製這則訊息',
    copyWithUrlSuccess: '已複製訊息與頁面連結',
    copyFail: '複製失敗',
    banSuccess: '已封鎖 @{username} 與他觸發的 AI 訊息',
    unbanSuccess: '已取消封鎖 @{username}',
    languageLabel: 'Interface Language 介面語言',
    languageDescription: '選擇介面與 AI 預設回覆語言；Auto 會跟隨瀏覽器語系。',
    languageAuto: 'Auto 跟隨瀏覽器',
    languageZhTw: '繁體中文',
    languageZhCn: '简体中文',
    languageEn: 'English',
    compatibilityLabel: 'Chat Protocol 聊天協定',
    compatibilityDescription: 'Legacy 使用目前 fork 協定；Upstream 會嘗試與原版 WebChat 公開聊天室互通。',
    compatibilityLegacy: 'Legacy',
    compatibilityUpstream: 'Upstream',
    aiLanguageInstruction: '請使用繁體中文回答，禁止使用簡體中文。',
    apiSettingsTitle: 'AI 服務設定',
    apiSettingsDescription: '設定 Groq API Key 與模型參數，供 AI 摘要與對話使用。',
    apiKeyRequired: '請輸入 API Key',
    apiLoadFailed: '載入 API 設定失敗',
    apiSaveSuccess: 'API 設定已保存',
    apiSaveFailed: 'API 設定保存失敗',
    apiKeyPlaceholder: '請輸入 Groq API Key',
    apiBaseUrlLabel: 'API Base URL',
    apiModelLabel: '模型名稱',
    apiDefaultPrefix: '預設',
    reset: '重設',
    saving: '儲存中...',
    save: '保存',
    githubProject: 'GitHub / 開源專案',
    versionInfo: '版本資訊',
    summaryTitle: 'AI 空間',
    summaryHistory: '歷史',
    summaryCloseTitle: '關閉 AI 空間',
    summaryOpenApiSettings: 'API 設定',
    summaryNeedApiKey: '請先設置 API Key',
    summaryEmptyIntro: '你可以直接和 AI 討論這個頁面，或先產生摘要再延伸追問。',
    summaryGenerate: '濃縮此網頁',
    summaryHostLabel: '網頁摘要',
    summaryUserLabel: '你',
    summaryAiLabel: 'AI',
    summaryAskPlaceholder: '直接問 AI 這個頁面的問題...',
    summaryApiApply: '申請 API Key',
    summarySettingsSaved: 'API 設定已保存',
    summarySettingsSaveFailed: 'API 設定保存失敗',
    summaryRetryFailed: '摘要失敗，請稍後再試',
    summaryAskFailed: '暫時無法回覆，請稍後再試',
    summaryNoPageText: '沒有取得頁面文字，仍可直接聊天，但摘要品質可能較差。',
    summaryPageReadFailed: '無法取得頁面內容',
    summaryExportMarkdownFilename: 'summary.md',
    summaryExportImageFilename: 'summary.png',
    summaryDirectChatInstruction: '不必先摘要，也可以直接提問。',
    summarySuggestedQuestions: '推薦問題',
    summarySuggestedIssues: '推薦議題',
    summarySuggestionsLoading: 'AI 正在觀察這個頁面...',
    summarySuggestionsDescription: '先挑一個方向，再決定是否追問。',
    chatSuggestionsTitle: '推薦議題',
    chatSuggestionsLoading: 'AI 正在整理這頁適合討論的方向...',
    chatSuggestionsDescription: '點一下可帶入輸入框，不會直接送出。',
    pageSuggestionChatLabel1: '這頁重點',
    pageSuggestionChatPrompt1: '這頁最值得一起討論的重點是什麼？',
    pageSuggestionChatLabel2: '不同看法',
    pageSuggestionChatPrompt2: '這個頁面內容可能有哪些不同看法？',
    pageSuggestionChatLabel3: '延伸問題',
    pageSuggestionChatPrompt3: '如果要延伸討論，大家最可能會問什麼？',
    pageSuggestionWorkspaceLabel1: '幫我整理',
    pageSuggestionWorkspacePrompt1: '幫我整理這頁的重點與脈絡。',
    pageSuggestionWorkspaceLabel2: '值得追問',
    pageSuggestionWorkspacePrompt2: '根據這頁內容，我下一步最值得問什麼？',
    pageSuggestionWorkspaceLabel3: '可能盲點',
    pageSuggestionWorkspacePrompt3: '這頁內容有哪些可能忽略的盲點或背景？',
    profileUsernameLabel: '使用者名稱',
    profileUsernamePlaceholder: '請輸入暱稱',
    profileUsernameDescription: '這是顯示給其他人的暱稱。',
    profileRandomAvatar: '隨機頭像',
    profileDanmakuLabel: '開啟彈幕',
    profileDanmakuDescription: '開啟後會在頁面上顯示彈幕訊息。',
    profileDanmakuOpacity: '彈幕透明度',
    profileDanmakuSpeed: '彈幕速度',
    profileSlow: '慢',
    profileNormal: '正常',
    profileFast: '快',
    profileShowFloatingButtons: '顯示右側懸浮按鈕',
    profileShowFloatingButtonsDescription: '在螢幕右側顯示聊天和 AI 摘要的懸浮按鈕。如果隱藏，也可點擊瀏覽器工具列上的擴充功能圖示重新顯示。',
    profileDeveloperMode: '開發者模式',
    profileDeveloperModeDescription: '顯示跨網站在線狀態與站點切換除錯介面；預設一般使用者不會看到。',
    profileHideAllAiMessages: '隱藏全部 AI 訊息',
    profileHideAllAiMessagesDescription: '僅在你的本地畫面隱藏所有 AI 聊天回覆，不影響其他使用者。',
    profileAiTopicSuggestions: '啟用 AI 推薦議題',
    profileAiTopicSuggestionsDescription: '在聊天與 AI 空間顯示由 AI 根據當前頁面產生的推薦問題與討論議題。點擊只會帶入輸入框，不會自動送出。',
    profileNotificationLabel: '開啟桌面通知',
    profileNotificationAll: '全部訊息',
    profileNotificationAt: '只在 @ 我時',
    profileNotificationDescription: '開啟後會顯示桌面通知。',
    profileThemeMode: '主題模式',
    profileThemeDescription: '套件顯示的主題模式；選擇「系統」即跟隨作業系統設定。',
    profileThemeSystem: '系統',
    profileThemeLight: '亮色',
    profileThemeDark: '暗色',
    profileSaved: '儲存成功'
  },
  zh_CN: {
    me: '我',
    aiInvokeLabel: '@ai',
    aiInvokeDescription: '调用房间 AI',
    aiInsertTitle: '插入 @ai 指令',
    aiPromptPlaceholder: '输入消息... 输入 @ai 可调用房间 AI',
    privateChatPlaceholder: '发送私聊消息给 @{username}...',
    privateChatActive: '私聊中（仅发送给 @{username}）',
    cancel: '取消',
    aiUnsupportedInPrivate: '@ai 目前不支持私聊模式。',
    aiPromptRequired: '请在 @ai 后面输入问题。',
    aiBusy: 'AI 还在回复上一条问题，请稍候。',
    aiCooldown: '@ai 冷却中，请 30 秒后再试。',
    aiLoading: 'AI 正在整理回复...',
    aiReplied: 'AI 已回复到聊天室',
    aiReplyFailed: 'AI 回复失败，请稍后再试。',
    aiMessageTitle: 'AI 消息',
    privateChatTitle: '点击开始私聊',
    privateChatCancelTitle: '取消私聊',
    privateChatBadge: '私聊',
    privateMessageTo: '私密发送给 @{username}',
    privateMessageIncoming: '私密消息',
    emptyMessage: '消息不能为空。',
    messageTooLarge: '消息大小不能超过 256KiB。',
    userOffline: '该用户已离线，无法进行私聊。',
    messageLimitReached: '已达到消息长度上限（{max} 字符）。',
    sendMessage: '发送',
    chatTab: '聊天',
    aiTab: 'AI',
    insertPageLink: '插入当前页面链接',
    closeChat: '关闭聊天',
    hideFloatingButtons: '隐藏悬浮按钮',
    hideFloatingButtonsSuccess: '悬浮按钮已完全隐藏，可在扩展设置页面重新显示。',
    chatButtonTitle: '聊天室',
    summaryButtonTitle: '网页摘要与对话',
    themeButtonTitle: '切换主题',
    settingsButtonTitle: '设置',
    emptyRoomTitle: '目前聊天室还没有人发言。',
    emptyRoomDescription: '输入消息并按下 Enter 开始聊天。',
    setupNamePlaceholder: '输入你的昵称...',
    setupAvatarHint: '点击头像可以随机更换头像',
    setupStart: '开始聊天',
    avatarFileTypeError: '仅支持 PNG、JPEG、WebP 图片',
    copied: '已复制',
    copy: '复制',
    copyWithUrl: '含链接复制',
    copyMessageTitle: '复制这条消息',
    copyWithUrlTitle: '复制这条消息与来源页面链接',
    copiedTitle: '已复制',
    openPage: '打开页面',
    openPageTitle: '打开这条消息对应的原始页面',
    pageLabel: '页面',
    ban: '封锁',
    unban: '取消封锁',
    banTitle: '封锁此人与他触发的 AI',
    unbanTitle: '取消封锁此人',
    likeTitle: '点赞',
    dislikeTitle: '倒赞',
    copySuccess: '已复制这条消息',
    copyWithUrlSuccess: '已复制消息与页面链接',
    copyFail: '复制失败',
    banSuccess: '已封锁 @{username} 与他触发的 AI 消息',
    unbanSuccess: '已取消封锁 @{username}',
    languageLabel: 'Interface Language 界面语言',
    languageDescription: '选择界面与 AI 默认回复语言；Auto 会跟随浏览器语言。',
    languageAuto: 'Auto 跟随浏览器',
    languageZhTw: '繁體中文',
    languageZhCn: '简体中文',
    languageEn: 'English',
    compatibilityLabel: 'Chat Protocol 聊天协议',
    compatibilityDescription: 'Legacy 使用当前 fork 协议；Upstream 会尝试与原版 WebChat 公开聊天室互通。',
    compatibilityLegacy: 'Legacy',
    compatibilityUpstream: 'Upstream',
    aiLanguageInstruction: '请使用简体中文回答。',
    apiSettingsTitle: 'AI 服务设置',
    apiSettingsDescription: '设置 Groq API Key 与模型参数，供 AI 摘要与对话使用。',
    apiKeyRequired: '请输入 API Key',
    apiLoadFailed: '加载 API 设置失败',
    apiSaveSuccess: 'API 设置已保存',
    apiSaveFailed: 'API 设置保存失败',
    apiKeyPlaceholder: '请输入 Groq API Key',
    apiBaseUrlLabel: 'API Base URL',
    apiModelLabel: '模型名称',
    apiDefaultPrefix: '默认',
    reset: '重置',
    saving: '保存中...',
    save: '保存',
    githubProject: 'GitHub / 开源项目',
    versionInfo: '版本信息',
    summaryTitle: 'AI 空间',
    summaryHistory: '历史',
    summaryCloseTitle: '关闭 AI 空间',
    summaryOpenApiSettings: 'API 设置',
    summaryNeedApiKey: '请先设置 API Key',
    summaryEmptyIntro: '你可以直接和 AI 讨论这个页面，或先生成摘要再继续追问。',
    summaryGenerate: '浓缩此网页',
    summaryHostLabel: '网页摘要',
    summaryUserLabel: '你',
    summaryAiLabel: 'AI',
    summaryAskPlaceholder: '直接问 AI 关于这个页面的问题...',
    summaryApiApply: '申请 API Key',
    summarySettingsSaved: 'API 设置已保存',
    summarySettingsSaveFailed: 'API 设置保存失败',
    summaryRetryFailed: '摘要失败，请稍后再试',
    summaryAskFailed: '暂时无法回复，请稍后再试',
    summaryNoPageText: '没有获取到页面文字，仍可直接聊天，但摘要质量可能较差。',
    summaryPageReadFailed: '无法获取页面内容',
    summaryExportMarkdownFilename: 'summary.md',
    summaryExportImageFilename: 'summary.png',
    summaryDirectChatInstruction: '无需先摘要，也可以直接提问。',
    summarySuggestedQuestions: '推荐问题',
    summarySuggestedIssues: '推荐议题',
    summarySuggestionsLoading: 'AI 正在观察这个页面...',
    summarySuggestionsDescription: '先选一个方向，再决定是否继续追问。',
    chatSuggestionsTitle: '推荐议题',
    chatSuggestionsLoading: 'AI 正在整理这个页面适合讨论的方向...',
    chatSuggestionsDescription: '点击即可带入输入框，不会直接发送。',
    pageSuggestionChatLabel1: '这页重点',
    pageSuggestionChatPrompt1: '这页最值得一起讨论的重点是什么？',
    pageSuggestionChatLabel2: '不同看法',
    pageSuggestionChatPrompt2: '这个页面内容可能有哪些不同看法？',
    pageSuggestionChatLabel3: '延伸问题',
    pageSuggestionChatPrompt3: '如果要延伸讨论，大家最可能会问什么？',
    pageSuggestionWorkspaceLabel1: '帮我整理',
    pageSuggestionWorkspacePrompt1: '帮我整理这页的重点与脉络。',
    pageSuggestionWorkspaceLabel2: '值得追问',
    pageSuggestionWorkspacePrompt2: '根据这页内容，我下一步最值得问什么？',
    pageSuggestionWorkspaceLabel3: '可能盲点',
    pageSuggestionWorkspacePrompt3: '这页内容有哪些可能忽略的盲点或背景？',
    profileUsernameLabel: '用户名',
    profileUsernamePlaceholder: '请输入昵称',
    profileUsernameDescription: '这是显示给其他人的昵称。',
    profileRandomAvatar: '随机头像',
    profileDanmakuLabel: '开启弹幕',
    profileDanmakuDescription: '开启后会在页面上显示弹幕消息。',
    profileDanmakuOpacity: '弹幕透明度',
    profileDanmakuSpeed: '弹幕速度',
    profileSlow: '慢',
    profileNormal: '正常',
    profileFast: '快',
    profileShowFloatingButtons: '显示右侧悬浮按钮',
    profileShowFloatingButtonsDescription: '在屏幕右侧显示聊天和 AI 摘要的悬浮按钮。如果隐藏，也可以点击浏览器工具栏上的扩展图标重新显示。',
    profileDeveloperMode: '开发者模式',
    profileDeveloperModeDescription: '显示跨网站在线状态与站点切换调试界面；默认普通用户不会看到。',
    profileHideAllAiMessages: '隐藏全部 AI 消息',
    profileHideAllAiMessagesDescription: '仅在你的本地画面隐藏所有 AI 聊天回复，不影响其他用户。',
    profileAiTopicSuggestions: '启用 AI 推荐议题',
    profileAiTopicSuggestionsDescription: '在聊天与 AI 空间显示由 AI 根据当前页面生成的推荐问题与讨论议题。点击只会带入输入框，不会自动发送。',
    profileNotificationLabel: '开启桌面通知',
    profileNotificationAll: '全部消息',
    profileNotificationAt: '仅在 @ 我时',
    profileNotificationDescription: '开启后会显示桌面通知。',
    profileThemeMode: '主题模式',
    profileThemeDescription: '扩展显示的主题模式；选择“系统”即跟随操作系统设置。',
    profileThemeSystem: '系统',
    profileThemeLight: '亮色',
    profileThemeDark: '暗色',
    profileSaved: '保存成功'
  },
  en: {
    me: 'me',
    aiInvokeLabel: '@ai',
    aiInvokeDescription: 'Call room AI',
    aiInsertTitle: 'Insert @ai command',
    aiPromptPlaceholder: 'Type a message... use @ai to call the room AI',
    privateChatPlaceholder: 'Send a private message to @{username}...',
    privateChatActive: 'Private chat active (only sending to @{username})',
    cancel: 'Cancel',
    aiUnsupportedInPrivate: '@ai is not available in private chat yet.',
    aiPromptRequired: 'Please type a prompt after @ai.',
    aiBusy: 'AI is still replying to the previous request.',
    aiCooldown: '@ai is cooling down. Please try again in 30 seconds.',
    aiLoading: 'AI is preparing a reply...',
    aiReplied: 'AI replied to the chat room.',
    aiReplyFailed: 'AI reply failed. Please try again later.',
    aiMessageTitle: 'AI message',
    privateChatTitle: 'Click to start private chat',
    privateChatCancelTitle: 'Cancel private chat',
    privateChatBadge: 'Private',
    privateMessageTo: 'Private to @{username}',
    privateMessageIncoming: 'Private message',
    emptyMessage: 'Message cannot be empty.',
    messageTooLarge: 'Message size cannot exceed 256KiB.',
    userOffline: 'This user is offline and private chat is unavailable.',
    messageLimitReached: 'Message length limit reached ({max} chars).',
    sendMessage: 'Send',
    chatTab: 'Chat',
    aiTab: 'AI',
    insertPageLink: 'Insert current page link',
    closeChat: 'Close chat',
    hideFloatingButtons: 'Hide floating buttons',
    hideFloatingButtonsSuccess: 'Floating buttons are hidden. You can re-enable them in extension settings.',
    chatButtonTitle: 'Chat room',
    summaryButtonTitle: 'Page summary and chat',
    themeButtonTitle: 'Toggle theme',
    settingsButtonTitle: 'Settings',
    emptyRoomTitle: 'No one has spoken in this room yet.',
    emptyRoomDescription: 'Type a message and press Enter to start chatting.',
    setupNamePlaceholder: 'Enter your nickname...',
    setupAvatarHint: 'Click the avatar to randomize it',
    setupStart: 'Start chatting',
    avatarFileTypeError: 'Only PNG, JPEG, and WebP images are supported',
    copied: 'Copied',
    copy: 'Copy',
    copyWithUrl: 'Copy + URL',
    copyMessageTitle: 'Copy this message',
    copyWithUrlTitle: 'Copy this message together with the source page URL',
    copiedTitle: 'Copied',
    openPage: 'Open page',
    openPageTitle: 'Open the original page for this message',
    pageLabel: 'Page',
    ban: 'Ban',
    unban: 'Unban',
    banTitle: 'Ban this user and their AI replies',
    unbanTitle: 'Unban this user',
    likeTitle: 'Like',
    dislikeTitle: 'Dislike',
    copySuccess: 'Message copied',
    copyWithUrlSuccess: 'Message and page URL copied',
    copyFail: 'Copy failed',
    banSuccess: 'Banned @{username} and their AI replies',
    unbanSuccess: 'Unbanned @{username}',
    languageLabel: 'Interface Language',
    languageDescription: 'Choose the UI language and default AI reply language. Auto follows the browser language.',
    languageAuto: 'Auto',
    languageZhTw: 'Traditional Chinese',
    languageZhCn: 'Simplified Chinese',
    languageEn: 'English',
    compatibilityLabel: 'Chat Protocol',
    compatibilityDescription: 'Legacy uses the current fork protocol. Upstream attempts public-room interoperability with the original WebChat.',
    compatibilityLegacy: 'Legacy',
    compatibilityUpstream: 'Upstream',
    aiLanguageInstruction: 'Respond in English.',
    apiSettingsTitle: 'AI Service Settings',
    apiSettingsDescription: 'Configure the Groq API key and model parameters used by AI summary and chat.',
    apiKeyRequired: 'Please enter an API key',
    apiLoadFailed: 'Failed to load API settings',
    apiSaveSuccess: 'API settings saved',
    apiSaveFailed: 'Failed to save API settings',
    apiKeyPlaceholder: 'Enter your Groq API key',
    apiBaseUrlLabel: 'API Base URL',
    apiModelLabel: 'Model Name',
    apiDefaultPrefix: 'Default',
    reset: 'Reset',
    saving: 'Saving...',
    save: 'Save',
    githubProject: 'GitHub / Open Source',
    versionInfo: 'Version info',
    summaryTitle: 'AI Workspace',
    summaryHistory: 'History',
    summaryCloseTitle: 'Close AI workspace',
    summaryOpenApiSettings: 'API settings',
    summaryNeedApiKey: 'Please set an API key first',
    summaryEmptyIntro: 'You can chat with AI about this page directly, or generate a summary first.',
    summaryGenerate: 'Summarize this page',
    summaryHostLabel: 'Page summary',
    summaryUserLabel: 'You',
    summaryAiLabel: 'AI',
    summaryAskPlaceholder: 'Ask AI about this page directly...',
    summaryApiApply: 'Get API Key',
    summarySettingsSaved: 'API settings saved',
    summarySettingsSaveFailed: 'Failed to save API settings',
    summaryRetryFailed: 'Summary failed. Please try again later.',
    summaryAskFailed: 'Unable to reply right now. Please try again later.',
    summaryNoPageText: 'No page text was captured. You can still chat directly, but summaries may be weaker.',
    summaryPageReadFailed: 'Failed to read page content',
    summaryExportMarkdownFilename: 'summary.md',
    summaryExportImageFilename: 'summary.png',
    summaryDirectChatInstruction: 'You do not need to summarize first before asking.',
    summarySuggestedQuestions: 'Recommended Questions',
    summarySuggestedIssues: 'Suggested Issues',
    summarySuggestionsLoading: 'AI is scanning this page...',
    summarySuggestionsDescription: 'Pick a direction first, then ask or refine it.',
    chatSuggestionsTitle: 'Suggested Topics',
    chatSuggestionsLoading: 'AI is drafting a few discussion starters for this page...',
    chatSuggestionsDescription: 'Click to insert into the input box. Nothing is sent automatically.',
    pageSuggestionChatLabel1: 'Page focus',
    pageSuggestionChatPrompt1: 'What is the most discussion-worthy point on this page?',
    pageSuggestionChatLabel2: 'Different views',
    pageSuggestionChatPrompt2: 'What different viewpoints could people have about this page?',
    pageSuggestionChatLabel3: 'Next question',
    pageSuggestionChatPrompt3: 'What is a good follow-up discussion question for this page?',
    pageSuggestionWorkspaceLabel1: 'Summarize it',
    pageSuggestionWorkspacePrompt1: 'Summarize the key ideas and context of this page.',
    pageSuggestionWorkspaceLabel2: 'What to ask',
    pageSuggestionWorkspacePrompt2: 'Based on this page, what is the most useful next question to ask?',
    pageSuggestionWorkspaceLabel3: 'Blind spots',
    pageSuggestionWorkspacePrompt3: 'What blind spots or missing context should I watch for on this page?',
    profileUsernameLabel: 'Username',
    profileUsernamePlaceholder: 'Enter your nickname',
    profileUsernameDescription: 'This is your public display name.',
    profileRandomAvatar: 'Random Avatar',
    profileDanmakuLabel: 'Enable Danmaku',
    profileDanmakuDescription: 'Show scrolling chat messages on the website.',
    profileDanmakuOpacity: 'Danmaku Opacity',
    profileDanmakuSpeed: 'Danmaku Speed',
    profileSlow: 'Slow',
    profileNormal: 'Normal',
    profileFast: 'Fast',
    profileShowFloatingButtons: 'Show Floating Buttons',
    profileShowFloatingButtonsDescription: 'Show floating chat and AI summary buttons on the right side. If hidden, you can reopen them from the extension icon.',
    profileDeveloperMode: 'Developer Mode',
    profileDeveloperModeDescription: 'Show cross-site presence and site-switch/debug UI in the header. Hidden from normal users by default.',
    profileHideAllAiMessages: 'Hide All AI Messages',
    profileHideAllAiMessagesDescription: 'Hide all AI-generated chat replies locally without affecting other users.',
    profileAiTopicSuggestions: 'Enable AI Topic Suggestions',
    profileAiTopicSuggestionsDescription: 'Show AI-generated recommended questions and discussion starters in chat and AI workspace. Clicking only inserts text into the input box.',
    profileNotificationLabel: 'Enable Notifications',
    profileNotificationAll: 'All messages',
    profileNotificationAt: 'Only when @mentioned',
    profileNotificationDescription: 'Show desktop notifications for messages.',
    profileThemeMode: 'Theme Mode',
    profileThemeDescription: 'The extension display theme. System follows the OS setting.',
    profileThemeSystem: 'System',
    profileThemeLight: 'Light',
    profileThemeDark: 'Dark',
    profileSaved: 'Saved successfully'
  }
} as const

export const getUiText = (preference?: AppLocalePreference) => TEXT[resolveAppLocale(preference)]
